[docs] Editing typos of the sds-replicated-volume module and general refactoring of docs
deckhouse/sds-replicated-volume pull request #205
Opened 2024-12-12 13:29 UTC by mortelumina98

## Description
Editing typos of the sds-replicated-volume module and general refactoring of docs.

## Why do we need it, and what problem does it solve?

## What is the expected result?

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

2024-12-13 14:37 UTC, Zhbert requested changes

2024-12-13 14:37 UTC, Zhbert commented on docs/FAQ_RU.md
> +Воспользуйтесь настройкой `drbdPortRange`. По умолчанию для DRBD-ресурсов используются TCP порты 7000-7999. С помощью `minPort` и `maxPort` эти значения можно переопределить.
```suggestion
Воспользуйтесь настройкой `drbdPortRange`. По умолчанию для DRBD-ресурсов используются TCP-порты 7000-7999. С помощью `minPort` и `maxPort` эти значения можно переопределить.
```

2024-12-13 14:37 UTC, Zhbert commented on docs/FAQ_RU.md
> +После изменения параметров `drbdPortRange` `minPort` и `maxPort`, перезапуск контроллера LINSTOR обязателен для применения новых настроек.
```suggestion
После изменения параметров `drbdPortRange`, `minPort` и `maxPort` перезапуск контроллера LINSTOR обязателен для применения новых настроек.
```

2024-12-13 14:37 UTC, Zhbert commented on docs/FAQ_RU.md
> +1. Переведите узел в состояние drain:
```suggestion
1. Выполните drain узла:
```

2024-12-13 14:37 UTC, Zhbert commented on docs/FAQ_RU.md
> +1. Проверьте, что в DRBD нет проблемных ресурсов или ресурсов в SyncTarget. Если они есть, дождитесь синхронизации или примите меры для восстановления нормальной работоспособности.
```suggestion
1. Проверьте, что в DRBD нет проблемных ресурсов или ресурсов в `SyncTarget`. Если они есть, дождитесь синхронизации или примите меры для восстановления нормальной работоспособности.
```

2024-12-13 14:37 UTC, Zhbert commented on docs/FAQ_RU.md
> +1. Перезагрузите узел, и дождитесь синхронизации **всех** DRBD-ресурсов. Выполните uncordon узла. При необходимости перезагрузки еще одного узла — повторитt алгоритм.
```suggestion
1. Перезагрузите узел и дождитесь синхронизации **всех** DRBD-ресурсов. Выполните uncordon узла. При необходимости перезагрузки еще одного узла — повторите алгоритм.
```

2024-12-13 14:37 UTC, Zhbert commented on docs/FAQ_RU.md
> +1. Переместите ресурсы на другой узел (только 1-2 ресурса одновременно):
```suggestion
1. Переместите ресурсы на другой узел (не более 1-2 ресурсов одновременно):
```

2024-12-13 14:37 UTC, Zhbert commented on docs/FAQ_RU.md
> +  Если файл отсутствует, значит, модуль не загружен и проблема не в этом.
```suggestion
  Если файл отсутствует, значит модуль не загружен и проблема не в этом.
```

2024-12-13 14:37 UTC, Zhbert commented on docs/FAQ_RU.md
> +Если под завис на стадии `ContainerCreating`, а в выводе команды `kubectl describe pod` присутствуют ошибки вроде той, что представлена ниже, значит, устройство смонтировано на одном из других узлов:
```suggestion
Если под завис на стадии `ContainerCreating`, а в выводе команды `kubectl describe pod` присутствуют ошибки вроде той, что представлена ниже, значит устройство смонтировано на одном из других узлов:
```

2024-12-13 14:37 UTC, Zhbert commented on docs/FAQ_RU.md
> +Далее получите список секретов по метке, дешифруйте данные, и поместите данные резервной копии в архив:
```suggestion
Далее получите список секретов по метке, дешифруйте данные и поместите данные резервной копии в архив:
```

2024-12-13 14:37 UTC, Zhbert commented on docs/LAYOUTS_RU.md
> +Работоспособность модуля гарантируется только при соблюдении системных [требований](./readme.html#системные-требования-и-рекомендации).
```suggestion
Работоспособность модуля гарантируется только при соблюдении [системных требований](./readme.html#системные-требования-и-рекомендации).
```

2024-12-13 14:37 UTC, Zhbert commented on docs/README_RU.md
> +Работоспособность модуля гарантируется только при соблюдении системных [требований](./readme.html#системные-требования-и-рекомендации).
```suggestion
Работоспособность модуля гарантируется только при соблюдении [системных требований](./readme.html#системные-требования-и-рекомендации).
```

2024-12-13 14:37 UTC, Zhbert commented on docs/README_RU.md
> +Модуль управляет реплицируемым блочным хранилищем на основе DRBD, с использованием LINSTOR в качестве управляющего слоя (control plane). Позволяет создавать Storage Pool в LINSTOR и StorageClass в Ku
```suggestion
Модуль управляет реплицируемым блочным хранилищем на основе DRBD с использованием LINSTOR в качестве управляющего слоя (control plane). Позволяет создавать Storage Pool в LINSTOR и StorageClass в Kubernetes через создание [пользовательских ресурсов Kubernetes](./cr.html).
```

2024-12-13 14:37 UTC, Zhbert commented on docs/README_RU.md
> +  После активации модуля `sds-replicated-volume` в конфигурации Deckhouse кластер автоматически настроится на работу с бэкендом LINSTOR. Вам останется лишь выполнить создание [пулы хранения и Storage
```suggestion
  После активации модуля `sds-replicated-volume` в конфигурации Deckhouse кластер автоматически настроится на работу с бэкендом LINSTOR. Вам останется лишь выполнить создание [пулов хранения и StorageClass'ов](./usage.html#конфигурация-бэкенда-linstor).
```

2024-12-13 14:37 UTC, Zhbert commented on docs/README_RU.md
> +У каждого из них есть свои особенности, преимущества и ограничения. Подробнее о различиях можно узнать в [FAQ](./faq.html#когда-следует-использовать-lvm-а-когда-lvmthin).
```suggestion
У каждого из них есть свои особенности, преимущества и ограничения. Подробнее о различиях можно узнать [в FAQ](./faq.html#когда-следует-использовать-lvm-а-когда-lvmthin).
```

2024-12-13 14:37 UTC, Zhbert commented on docs/README_RU.md
> +1. Активируйте модуль `sds-replicated-volume`. Перед включением рекомендуется ознакомиться с [доступными настройками](./configuration.html).
```suggestion
1. Активируйте модуль `sds-replicated-volume`. Перед включением рекомендуется ознакомиться [с доступными настройками](./configuration.html).
```

2024-12-13 14:37 UTC, Zhbert commented on docs/README_RU.md
> +Для настройки хранилища на узлах необходимо создать группы томов LVM с использованием ресурсов LVMVolumeGroup. В данном примере создается хранилище Thick. Подробнее про пользовательские ресурсы и при
```suggestion
Для настройки хранилища на узлах необходимо создать группы томов LVM с использованием ресурсов LVMVolumeGroup. В данном примере создается хранилище Thick. Подробнее про пользовательские ресурсы и примеры их использования можно прочитать [в примерах использования](./usage.html).
```

2024-12-13 14:37 UTC, Zhbert commented on docs/README_RU.md
> +     name: "vg-1-on-worker-0" # Имя может быть любым подходящим для имен ресурсов в Kubernetes. Именно это имя ресурса LVMVolumeGroup будет в дальнейшем использоваться для создания ReplicatedStorageP
```suggestion
     name: "vg-1-on-worker-0" # Имя может быть любым подходящим для имен ресурсов в Kubernetes. Именно это имя ресурса LVMVolumeGroup будет в дальнейшем использоваться для создания ReplicatedStoragePool.
```

2024-12-13 14:37 UTC, Zhbert commented on docs/README_RU.md
> +     actualVGNameOnTheNode: "vg-1" # Имя LVM VG, которая будет создана на узле из указанных выше блочных устройств
```suggestion
     actualVGNameOnTheNode: "vg-1" # Имя LVM VG, которая будет создана на узле из указанных выше блочных устройств.
```

2024-12-13 14:37 UTC, Zhbert commented on docs/README_RU.md
> +     lvmVolumeGroups: # Здесь указываем имена ресурсов LVMVolumeGroup, которые мы создавали ранее
```suggestion
     lvmVolumeGroups: # Здесь указываем имена ресурсов LVMVolumeGroup, которые мы создавали ранее.
```

2024-12-13 14:37 UTC, Zhbert commented on docs/README_RU.md
> +     storagePool: data # Указываем имя ReplicatedStoragePool, созданного ранее
```suggestion
     storagePool: data # Имя ReplicatedStoragePool, созданного ранее.
```

2024-12-13 14:37 UTC, Zhbert commented on docs/README_RU.md
> +     topology: Ignored # - если указываем такую топологию, то в кластере не должно быть зон (узлов с метками topology.kubernetes.io/zone).
```suggestion
     topology: Ignored # Если указана такая топология, то в кластере не должно быть зон (узлов с метками topology.kubernetes.io/zone).
```

2024-12-13 14:37 UTC, Zhbert commented on docs/README_RU.md
> +- Используйте стоковые ядра, поставляемые вместе с [поддерживаемыми дистрибутивами](https://deckhouse.ru/documentation/v1/supported_versions.html#linux).
```suggestion
- Используйте стоковые ядра, поставляемые вместе [с поддерживаемыми дистрибутивами](https://deckhouse.ru/documentation/v1/supported_versions.html#linux).
```

2024-12-13 14:37 UTC, Zhbert commented on docs/README_RU.md
> +- Не используйте RAID. Подробнее в [FAQ](./faq.html#почему-не-рекомендуется-использовать-raid-для-дисков-которые-используются-модулем-sds-replicated-volume).
```suggestion
- Не используйте RAID. Подробнее [в FAQ](./faq.html#почему-не-рекомендуется-использовать-raid-для-дисков-которые-используются-модулем-sds-replicated-volume).
```

2024-12-13 14:37 UTC, Zhbert commented on docs/README_RU.md
> +- Используйте локальные физические диски. Подробнее в [FAQ](./faq.html#почему-вы-рекомендуете-использовать-локальные-диски-не-nas).
```suggestion
- Используйте локальные физические диски. Подробнее [в FAQ](./faq.html#почему-вы-рекомендуете-использовать-локальные-диски-не-nas).
```

2024-12-25 11:25 UTC, mortelumina98 commented on docs/FAQ_RU.md
> +   > **Внимание.** Эта информация отражает состояние всего доступного пространства в кластере.  Если необходимо создать тома в двух репликах, то эти значения стоит делить на два, чтобы получить предс
the numbering will break

2024-12-25 11:27 UTC, mortelumina98 commented on docs/FAQ_RU.md
> +- LVM — это более простой вариант, который обеспечивает высокую производительность, близкую к производительности самого накопителя. Однако LVM не поддерживает использование snapshot'ов.
+

2024-12-25 12:13 UTC, Zhbert approved these changes

2024-12-25 12:23 UTC, z9r5 submitted a review, later dismissed

2025-01-31 11:40 UTC, MrTomSawyer commented
@mortelumina98 Hi! I've resolved all the conflicts. Could you please take a look at the README and README_RU? It seems that some parts of the guide might be missing. Please ensure that the text is up to date.

2025-02-03 11:50 UTC, z9r5 approved these changes

2025-02-03 16:27 UTC, AleksZimin approved these changes

2025-02-03 16:29 UTC, merged